subhadipbhowmik/30-Days-Of-CPP

README.md
=> Corrected -About- Spelling in readme File

src/components/HomepageFeatures/index.js, src/components/HomepageFeatures/styles.module.css
Closes #29 
Changed 2 files- index.js and styles.module.css
Added hover card effect on Home Page features
https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/98379619/434882cc-4868-4840-962d-f280e0779f9d
Kindly verify and merge.
=> added hover card effect

.github/ISSUE_TEMPLATE/documentation.md
=> Added documentation issues templates

docusaurus.config.js, siteConfig.js, src/css/custom.css, src/pages/login.md, src/pages/signup.md
Fixes #11 
The project has undergone the following changes:
- Added Sign Up and Login buttons to the navigation bar.
- Created dedicated web pages for sign-up and login.
https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/153659573/751f2270-c930-4cb5-846d-26d2f229eec7
Requesting you to please label the PR before merging.
Thank you! Happy Coding!
=> FIXED #11 : Added Sign-Up and Login Pages

src/components/HomepageFeatures/index.js, src/components/HomepageFeatures/styles.module.css
Fixes Issue No #34
The UI Glitch has been fixed now, words used to protrude outside the box earlier, which has been fixed now.
Fixing UI gives the finished look to any final product
I have tested it locally. Here's the Screenshot
Now :- 
Earlier :-
=> Bug Fix : Fixes bug No. #34 UI Glitch 

src/components/HomepageFeatures/styles.module.css
The paragraph text is getting outside of container .
=> fixed paragraph getting outside of box

package-lock.json, package.json, src/components/Chatbot/chatbot.js, src/components/Chatbot/style.css, src/components/Chatbot/stylr.css, src/pages/index.js
Fixes Issue No :- #16 
**Description**
This AI chatbot is based on the GPT-3.5 It can answer questions, offer information and provide 24/7 assistance, enhancing user experience through efficient and effective interactions. 
Requesting you to please label the PR before merging.
=> Added AI Chatbot

src/pages/index.js, src/pages/index.module.css
------------------------------
**Made all the required changes** 
Styles--->
1. modification in Index.module.css
2. added classes to src/pages.index.js
This will fulfill the requirement.
=> added custom styles to hero section

src/css/custom.css
#PR Description
Login and signup container's font color changed as in dark mode, it was of same color as background. Now, the font is visible in both dark mode and light mode.
#fixes 68
#Screenshots
=> changed login/signup font color in dark mode

src/components/Chatbot/style.css, src/components/HomepageFeatures/styles.module.css, src/components/Toast/toastStyles.css, src/css/custom.css, src/pages/index.module.css
Updated styles to turn off text selection
Closes #87 
I am contributing under GSSoC 2024
=> Updated styles to turn off text selection #87 resolved

docs/day-04/input-output-in-cpp.md
I have added the relevant content for Day 4 ,Input and Output in C++.
closes #85
=> Added Day 4 Content input-output-in-cpp.md

docs/day-07/ternary-operator.md
Closes #94 
Added content for Day 7 ternary operator by completing the mentioned tasks-
- What is the Ternary Operator in C++?
- Explain the Syntax of Ternary Operator in C++.
- How does the Ternary Operator work in C++?
- C++ Ternary Operator Example
- C++ Ternary Operator with Nested Ternary Operator
=> Added Day 7 Content - ternary operator

docs/day-02/first-cpp-program.md, src/css/custom.css, src/pages/login.js, src/pages/login.md
#Fixed Issue #78 
I have added some JavaScript to add a function to show and hide in the password field to enhance the user experience.
Video/ Screenshot:
https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/132553685/a22054c2-8a86-4716-a304-211fc5b92326
=> Added the Show/Hide Function in the login form

docs/day-05/if-else-statement.md
---------------
> Include Examples
> made point-wise content for better understanding
> Properly follow the listed question
=> Added Content in Day 5 IF-Else Statement

docs/day-07/switch-case-statement.md
=> Added the content of switch case 

docusaurus.config.js
Fixes: #141 
Fixed the spelling/grammatical error in the copyright section.
=> fixed-grammatical-error

src/css/custom.css
=> added scroll bar

docs/day-05/for-loop.md
Added the content for Day 05 For Loop.
Kindly Review and merge
=> Added Day5 ForLoop Content

docs/day-07/function-in-cpp.md
The website was missing the day 7 content which was the function one
So I added the content in following order:
- Function Definition
- Explain the Syntax of Function in C++.
- Types of Functions in C++
- How to Declare and Define a Function in C++?
- How to Call a Function in C++?
- C++ Function Example
- C++ Function with Parameters
- C++ Function with Return Value
- C++ Function with Default Arguments
- C++ Function with Function Overloading
- C++ Function with Recursion
- C++ Function with Inline Function
=> Day 07 added

src/pages/signup.js
Addition of Hide /Show Functionality in the Sign-up page is done .
https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/128716726/0b4fdab5-7f82-45e0-a925-5122b30003f3
=> Addition of Hide /Show Functionality in the Sign-up page done .

docs/day-12/Object_Oriented_Programming.md, docs/day-12/_category_.json
Closes #137 
>I have added content related to OOPS for Day 12. 
###Checklist
>I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/MIpaltan007/30-Days-Of-CPP/blob/main/CONTRIBUTING.md) before creating this pull request
=> Day12 - Added Day 12 Content

docs/day-06/continue-statement.md
Day 6 continue statement content is added #189
=>  #189 continue_statement added

src/pages/signup.md
Already have an account is now visible on signup page.
Fixes #55
=> Already have an account/ not clearly visible resolved

docs/day-09/array-in-function.md, docs/day-11/reference-in-cpp.md
Updating content in day 9: Array in Function in C++
=> Day 9: Array in Function 

.github/workflows/auto-comment-pr-merge.yml
closes #198 
I updated the comment POST code.
I have also tested this on my local repository and it worked.
=> Issue in autocommenting on merged pr #198

src/css/custom.css
Now it have same color as signup page
=> fixed color of already have an account

docs/day-07/function-in-cpp.md
provided with the best quality of content with syntax & Examples
=> Added Day 7 function content 

src/css/custom.css
Please review this changes and approve
fixes issue #103
**Before**
**After**
**Before**
**After**
=> I made changes in dark & light mode

src/pages/login.js
Issue #55 is Resolved for better user interface and better user experience.
=> Issue #55 Resolved

docs/day-10/string-class.md
#157 Day 10 string class content added
=> string class added

docs/day-10/string-in-cpp.md
=> Day 10 string in cpp added

docs/day-14/_category_.json, docs/day-14/constructor.md, docs/day-14/destructor.md, docs/day-14/typesofconstructor.md
day-14 content added
constructor and destructor
#170
=> day-14 content added

docs/day-09/array-in-cpp.md
Added solution to the question of Day - 09 : Array in CPP.
Fixes #245 #161
=> Update day 09 - Array in CPP

docs/day-11/pointers-in-cpp.md
Added the day-11 content for pointers in CPP in depth for easy and clear understanding. 
Fixes #132
=> Day-11 content added - Pointer in CPP

docs/day-09/recursion-in-cpp.md
Added more about recursion ,provided quality content with sufficient examples that everyone understand easily.
=> Added content of recursion 

docs/day-16/_category_.json, docs/day-16/function-overloading.md, docs/day-16/operator-overloading.md
Added Function & Operator Overloading.
Fixed Issue: #234
=> Added Day16

src/components/ScrollToTop/ScrollToTopButton.js, src/components/ScrollToTop/ScrollToTopButton.module.css
Hey @subhadipbhowmik 
I have added the scroll to top button and changed the position
Closes #223 
- The button only appear after the user has scrolled down a certain distance from the top of the page
- Designed as a small, round button with an arrow icon pointing upwards.
- Styling that matches the website’s overall design, with appropriate hover effects.
- When clicked, the button will smoothly scroll the user back to the top of the page.
https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/101971980/e45bafc2-f036-40d1-b7e9-a15137ec1ded
Please take a look and review it, Thank You!!
=> Added a "Better Scroll-to-top button" with fixed position

docs/day-11/pointers-in-array.md, package-lock.json
I have added more questions related to pointers in array. As pointers in array is very important topic as per interviews, keeping that in mind I have added related questions of it from easy to intermediate level.
This is the ScreenShot of the task that I have done
=> more questions are added related to  pointers in array

blog/2024-06-03-string-problems/string-problems.md
Added 12 more string question to string.md file
=> Added more string question : #267

blog/2024-06-03-sorting-problems/sorting-problems.md
Added 15 more sorting problems to sorting-problems.md file
closes #284
=> Added more sorting question : #284

docs/day-14/Create-References.md, docs/day-14/Memory-Address.md, docs/day-14/_category_.json
i have added c++ reference documentation solving issue no. #235
=> c++ reference documentation added

docs/day-15/Abstraction.md, docs/day-15/Encapsulation.md, docs/day-15/_category_.json
Fixes #179 
I have added the content for Day 15, which includes the topics of 'Encapsulation' and 'Abstraction'.
Kindly label my PR and assign it to me before merging it.
Thank You!
=> Fixes #179 : Added Content to Day 15

docs/day-10/multidimentional-array.md
=> multidimentional added

package-lock.json, src/components/ScrollToTop/ScrollToTopButton.module.css
Hey @subhadipbhowmik,
issue closes #250 
This PR addresses the alignment issues between the chatbox and the scroll-to-top button on the website. Previously, the chatbox was positioned at the rightmost bottom corner, and the scroll-to-top button was placed above it with a significant gap in between. This caused overlap issues when the chatbox was opened.
**Changes Made**:
- Moved the scroll-to-top button to the leftmost bottom corner of the website.
- Aligned the scroll-to-top button horizontally with the chatbox.
- Adjusted the CSS to ensure both elements are visually appealing and do not overlap.
Please take a look.
=> Resolved Allignment and Overlapping of Chatbox and Scroll-to-top button

src/pages/index.js
Fixes #309 
Changes made:
- Closed the main tag
- removed the script tags which created an error for addEventListener since the file is a javascript file so no need of the explicit script tag
- Removed the text "main" which was added unnecessarily
=> Fixed the error on index.js 

blog/2024-06-14-pointers-problems/pointers-problem.md
Added problems related to two pointers
closes #300
=> Added Pointers problems: #300

blog/2024-06-14-recursion-problem/recursion-problem.md
Added problems related to recursion
=> Added recursion problem: #301

src/css/custom.css
Professional Appearance: The scrollbar now has a professional appearance.
Scrollbar Thumb Color Matches Theme: The color of the scrollbar thumb now matches the overall theme.
Improved Design: This updated scrollbar design is an improvement over the previous version.
=> Stylish Scrollbar added

docs/day-02/comments-in-cpp.md, src/pages/index.js
Fixes #261 
I have added the content weight for main points to enhance the points.
=> Enhanced the comment page 

docs/day-02/comments-in-cpp.md, docs/day-07/function-in-cpp.md, docs/day-08/function-overloading.md, src/pages/index.js
Fixes #259 
Added function overloading content
=> Day 8 - Function overloading

docs/day-02/comments-in-cpp.md, docs/day-07/function-in-cpp.md, docs/day-08/function-overloading.md, docs/day-11/reference-in-cpp.md, src/pages/index.js
Fixes #258 
Added the reference content:
=> Day 11 - Reference 

blog/2024-06-03-array-problems/array-problems.md
Added more Array Problems to array-problems.md file in blog
closes #307
=> Added Array problems: #307

blog/2024-06-03-array-problems/array-problems.md, blog/2024-06-03-function-problems/function-problems.md
Added more functions problems to function-problems.md file in the blog
closes #311
=> Added Function problems #311

docs/day-11/pass-by-value.md, docs/day-11/reference-in-cpp.md, docs/day-11/reference-vs-pointers.md, docs/day-11/returning-by-reference.md
**Added Day 11 Pass By Value** 
**Solves** #345
Added with proper reading content along with examples
=> Added Day 11 Pass By Value 

blog/2021-06-15-dynamic-programming/dynamic-programming-problems.md
Added problems related to dynamic programming in blog
closes #338
=> Added Problem related to dynamic programming: #338

backend/.gitignore, backend/config/config.js, backend/controllers/authController.js, backend/controllers/errorHandler.js, backend/index.js, backend/middleware/authMiddleware.js, backend/middleware/validationMiddleware.js, backend/models/user.js, backend/package-lock.json, backend/package.json, backend/routers/auth.js, backend/routers/router.js
closes #356 
Here's a short summary of the changes made to the project structure and organization:
1. **File Organization**: 
- Introduced separate directories (`config`, `models`, `routes`, `controllers`, `middleware`) to organize different components of the application logically.
2. **Configuration (`config/config.js`)**:
- Centralized configuration variables (`JWT_SECRET`, `mongoURI`) into a dedicated file (`config/config.js`).
3. **User Model (`models/user.js`)**:
- Defined the Mongoose schema and model for the `User` entity in `models/user.js`.
4. **Routing (`routes/router.js` and `routes/auth.js`)**:
- Created a main router file (`routes/router.js`) to combine all route modules and mount them under `/api`.
- Implemented authentication routes (`/signup` and `/login`) in …
=> Improvement in backend file structure. #356

docs/day-14/category_.json, docs/day-14/stl-containers.md, docs/day-14/stl-iterators.md
=> Day -14 : C++ Standard Template Library (STL)

docs/day-22/Linear Search.md, docs/day-22/_category_.json
Added content about linear search in the docs as day 22 content.
closes #254
=> Added Linear search #254

src/pages/index.module.css
Hey @subhadipbhowmik issue closes #497 
I have Redesign "Vertical Scrollbar" Matching to the "Website Theme" 
Please take a look and review it.
=> Redesign "Vertical Scrollbar" Matching to the "Website Theme" 

package-lock.json, src/components/HomepageFeatures/styles.module.css
https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/119414762/ffaae118-4d3d-4f4c-a8c7-62c30253ad70
Here is the video of animation added in the Home Section.
Can you increase the level under Gssoc.
=> Animation added to the image

package-lock.json, src/components/Cursor.js, src/css/custom.css, src/pages/index.js
I have added animated glowing cursor to project.
=> added animated glowing cursor

blog/2024-06-25-Trie-problems/Trie-problems.md
I added the Trie problems in Blog. Each and every problem increases the understanding of trie and make them ready to tackle the real problems.
Closes #455
=> Trie in blog
